apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.nx_name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.nx_replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.nx_name }}
    spec:
      containers:
      - name: {{ .Values.nx_name }}
        image: "{{ .Values.nx_image.repository }}:{{ .Values.nx_image.version }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: ART_BASE_URL
          value: {{ .Values.nx_env.art_url }}
        - name: SSL
          value: "{{ .Values.nx_env.ssl }}"
        ports:
        - containerPort: {{ .Values.nx_service.internalPortHttp }}
        - containerPort: {{ .Values.nx_service.internalPortHttps }}
        volumeMounts:
        - mountPath: "/var/opt/jfrog/nginx"
          name: nginx-volume
        resources:
{{ toYaml .Values.nx_resources | indent 12 }}
      volumes:
      - name: nginx-volume
      {{- if .Values.nx_persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.nx_name }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
