apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.db_name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.db_name }}
    spec:
      containers:
      - name: {{ .Values.db_name }}
        image: "{{ .Values.db_image.repository }}:{{ .Values.db_image.version }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.db_env.db_name }}
        - name: POSTGRES_USER
          value: {{ .Values.db_env.db_user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.db_env.db_pass }}
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        ports:
        - containerPort: {{ .Values.db_service.internalPort }}
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgresql-volume
        resources:
{{ toYaml .Values.db_resources | indent 12 }}
      volumes:
      - name: postgresql-volume
      {{- if .Values.db_persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.db_name }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
